// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsxvdqcceypgygmoygoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzeHZkcWNjZXlwZ3lnbW95Z29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Njg3ODUsImV4cCI6MjA2MjA0NDc4NX0.fBuT6bW-MPjsp2TWaEHOsZEB1SzhZNVxHsD0bxtHG4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);